package:
  name: urbansim
  version: !!str 1.1

source:
  fn: urbansim-1.1.zip
  url: https://pypi.python.org/packages/source/u/urbansim/urbansim-1.1.zip
  md5: 00040a0ef41544b948376f1f31684bac
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - urbansim = urbansim:main
    #
    # Would create an entry point called urbansim that calls urbansim.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - bottle >=0.12.5
    - matplotlib >=1.3.1
    - numpy >=1.8.0
    - pandana >=0.1
    - pandas >=0.13.1
    - patsy >=0.2.1
    - prettytable >=0.7.2
    - pyyaml >=3.10
    - scipy >=0.13.3
    - simplejson >=3.3.3
    - statsmodels >=0.5.0
    - pytables >=3.1.0
    - toolz >=0.7.0

  run:
    - python
    - bottle >=0.12.5
    - matplotlib >=1.3.1
    - numpy >=1.8.0
    - pandana >=0.1
    - pandas >=0.13.1
    - patsy >=0.2.1
    - prettytable >=0.7.2
    - pyyaml >=3.10
    - scipy >=0.13.3
    - simplejson >=3.3.3
    - statsmodels >=0.5.0
    - pytables >=3.1.0
    - toolz >=0.7.0

test:
  # Python imports
  imports:
    - urbansim
    - urbansim.developer
    - urbansim.maps
    - urbansim.models
    - urbansim.sim
    - urbansim.urbanchoice
    - urbansim.utils

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/synthicity/urbansim
  license:  BSD License
  summary: 'Tool for modeling metropolitan real estate markets'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
