{% set name = "urbanaccess" %}
{% set version = "0.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b2d7905a42b896923508b4419b0809b1494eb5c5f0c5c62998df6ff8c6a3fd92

#build:
#  number: 0
#  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "

requirements:
  host:
    - geopy >=1.11.0
    - matplotlib >=2.0
    - numpy >=1.11
    - osmnet >=0.1.4
    - pandana =0.3.0
    - pandas >=0.17.0
    - pip
    - pip
    - python
    - pyyaml >=3.11
    - requests >=2.9.1
    - scikit-learn >=0.17.1
  run:
    - geopy >=1.11.0
    - matplotlib >=2.0
    - numpy >=1.11
    - osmnet >=0.1.4
    - pandana =0.3.0
    - pandas >=0.17.0
    - python
    - pyyaml >=3.11
    - requests >=2.9.1
    - scikit-learn >=0.17.1

test:
  imports:
    - urbanaccess
    - urbanaccess.gtfs
    - urbanaccess.osm

about:
  home: https://github.com/UDST/urbanaccess
  license: GNU Affero General Public v3
  summary: A tool for creating GTFS transit and OSM pedestrian networks for use in Pandana accessibility analyses.


extra:
  recipe-maintainers:
    - 13947822
