package:
  name: urbanaccess
  version: "0.1.0"

source:
  fn: urbanaccess-0.1.0.tar.gz
  url: https://files.pythonhosted.org/packages/08/b7/e65a53ac6688888ae20529e30cb02eb1e789aebd193ece31ec06db70a183/urbanaccess-0.1.0.tar.gz
  sha256: b2d7905a42b896923508b4419b0809b1494eb5c5f0c5c62998df6ff8c6a3fd92

#build:
#  number: 0
#  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "

requirements:
  build:
    - pip
    - python
    - setuptools
    - click >=6.7
    - python-dateutil >=2.6.1
    - scikit-learn >=0.17.1
    - pytz >=2018.5
    - geopy >=1.11.0
    - matplotlib >=2.0
    - numpy >=1.11
    - osmnet >=0.1.4
    - pandana =0.3.0
    - pandas >=0.17.0
    - pyyaml >=3.11
    - requests >=2.9.1
    - blas >=1.1
    - libgfortran >=3.0.0
    - openblas >=0.2.20
    - scipy >=1.1.0

  run:
    - pip
    - python
    - setuptools
    - click >=6.7
    - python-dateutil >=2.6.1
    - scikit-learn >=0.17.1
    - pytz >=2018.5
    - geopy >=1.11.0
    - matplotlib >=2.0
    - numpy >=1.11
    - osmnet >=0.1.4
    - pandana =0.3.0
    - pandas >=0.17.0
    - pyyaml >=3.11
    - requests >=2.9.1
    - blas >=1.1
    - libgfortran >=3.0.0
    - openblas >=0.2.20
    - scipy >=1.1.0


test:
  imports:
    - urbanaccess
    - urbanaccess.gtfs
    - urbanaccess.osm

about:
  home: https://github.com/UDST/urbanaccess
  license: GNU Affero General Public v3
  summary: A tool for creating GTFS transit and OSM pedestrian networks for use in Pandana accessibility analyses.

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
