package:
  name: pandana
  version: !!str 0.4.1

source:
  fn: pandana-0.4.1.tar.gz
  url: https://files.pythonhosted.org/packages/68/a6/2ac42b85ea5353370d40abde239493149a2a1974143881ff5c7208429daa/pandana-0.4.1.tar.gz
  sha256: bcdedb4eb21da0d1012e76c8af6ad2c31124bbcfc40274ab40ecbe0119560abd
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pandana = pandana:main
    #
    # Would create an entry point called pandana that calls pandana.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - cython >=0.25.2
    - brewer2mpl >=1.4
    - matplotlib >=1.3.1
    - mock
    - nose
    - numpy >=1.8.0
    - pandas >=0.13.1
    - pytables >=3.1.0
    - requests >=2.0
    - osmnet >=0.1.3
    - scikit-learn >=0.18.1
    - hdf5 >=1.8.0
    - geopandas >=0.2.1

  run:
    - python
    - setuptools
    - cython >=0.25.2
    - brewer2mpl >=1.4
    - matplotlib >=1.3.1
    - mock
    - nose
    - numpy >=1.8.0
    - pandas >=0.13.1
    - pytables >=3.1.0
    - requests >=2.0
    - osmnet >=0.1.3
    - scikit-learn >=0.18.1
    - hdf5 >=1.8.0
    - geopandas >=0.2.1

test:
  # Python imports
  imports:
    - pandana
    - pandana.network
    - pandana.cyaccess

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://udst.github.io/pandana/
  license:  GNU Affero General Public License v3
  summary: 'Pandas Network Analysis - dataframes of network queries, quickly'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
