package:
  name: pandana
  version: !!str 0.2.0

source:
  fn: pandana-0.2.0.zip
  url: https://pypi.python.org/packages/source/p/pandana/pandana-0.2.0.zip
  md5: 1cfd50ca505cb7629fa143a533f41d02
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pandana = pandana:main
    #
    # Would create an entry point called pandana that calls pandana.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - brewer2mpl >=1.4
    - matplotlib >=1.3.1
    - mock
    - nose
    - numpy >=1.8.0
    - pandas >=0.13.1
    - pytables >=3.1.0
    - requests >=2.0

  run:
    - python
    - brewer2mpl >=1.4
    - matplotlib >=1.3.1
    - mock
    - nose
    - numpy >=1.8.0
    - pandas >=0.13.1
    - pytables >=3.1.0
    - requests >=2.0

test:
  # Python imports
  imports:
    - pandana
    - pandana.network
    - pandana._pyaccess

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://udst.github.io/pandana/
  license:  GNU Affero General Public License v3
  summary: 'Pandas Network Analysis - dataframes of network queries, quickly'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
