{% set name = "orca-test" %}
{% set version = "0.1" %}

package:
  name: orca_test
  version: "0.1"

source:
  fn: orca_test-0.1.0.tar.gz
  url: https://files.pythonhosted.org/packages/96/a6/ab3c34c7d5a9db9c46b1701a5aab21dabc9e4f0eb74060e13f0ab39a0dd3/orca_test-0.1.0.tar.gz
  sha256: 6332ee808918b087e5bd5401ba254ee633d4000ce9c76aba069d9c1ec8dbc52e

#build:
#  number: 0
#  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "

requirements:
  build:
    - pip
    - python
    - setuptools
    - python-dateutil >=2.6.1
    - pytz >=2016.10
    - numpy >=1.0
    - pandas >=0.12
    - orca >=1.3.0
  run:
    - python
    - python-dateutil >=2.6.1
    - pytz >=2016.10
    - numpy >=1.0
    - pandas >=0.12
    - orca >=1.3.0

test:
  imports:
    - orca_test

about:
  home: https://github.com/urbansim/orca_test
  license: BSD License
  license_family: BSD
  summary: Assertions for testing the characteristics of orca tables and columns
